# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [3]:
# 1.Crear un arreglo de ceros de longitud 12
arr1 = np.zeros(12)
arr1


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 2.Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

arr2 = np.zeros(10)
arr2[4] = 10
arr2

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [7]:
# 3.Crear un arreglo que tenga los números del 10 al 49

arr3 = np.arange(10, 50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
# 4.Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

arr4 = np.arange(9).reshape(3,3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
# 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

arr5 = np.random.randint(1, 100, 100)
arr5

array([89, 97, 25,  8, 96, 46, 56, 20, 74, 74, 69, 14, 67, 17, 42, 18, 77,
       96, 23, 96, 41, 59, 82, 81, 15, 43, 98, 58, 79, 57, 55, 44, 30, 89,
       80, 92, 48, 53, 95,  9,  3, 51, 15, 53, 40, 80, 57, 53, 85, 71, 85,
       77, 56,  6, 61, 99, 20, 67, 99, 85, 53, 18,  3,  5, 86, 89, 33, 97,
       12, 71, 14, 26, 61, 62, 13, 82, 71, 80, 18, 88, 12, 48, 37, 79,  9,
       15, 49, 24, 16, 34, 24, 67, 59, 42, 32, 37, 42, 92, 20, 43])

In [32]:
media = np.mean(arr5)
media

52.38

In [33]:
varianza = np.var(arr5)
varianza

846.9956

In [38]:
# 6. Calcular la media de un arreglo usando np.sum

arr6 = np.sum(arr5) / arr5.size
arr6

52.38

In [42]:
# 7. Calcular la varianza de un arreglo usando np.sum y np.mean

media = np.mean(arr5)
print(media)

suma_total = np.sum((arr5 / media) ** 2)
print(suma)

varianza_arr5 = suma_total / arr5.size
varianza_arr5

52.38
130.8709622066022


1.308709622066022

In [49]:
# 8. Crear un array de números aleatorios usando np.random.randn

arr_aleatorios = np.random.randn(15)
arr_aleatorios

array([ 0.06205171, -1.53767409,  0.49355619,  1.30912213, -0.4489918 ,
       -0.97301305,  2.08976575,  0.09000819,  0.56283923,  0.8701262 ,
        1.07330389,  2.57667582, -0.51665329, -0.64611775,  0.47816676])